name: Your New Jekyll Site
markdown: kramdown
highlighter: true
port: 4000
permalink: /:categories/:year/:month/:day/:title

gems:
  - octopress-include-tag

# Collections
collections:
    notes:
        output: true